### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by ToniSnakes** [ToniSnakes/PiRoom#11]
- [ ] Login functionality
- [ ] User commands
    - [ ] List online users
    - [ ] List recent messages
        - [ ] Set up messages database
        - [ ] Implement commands that adapt based on how recent / the date on which messages were sent
    - [ ] Miscellaneous
        - [ ] HERE BE DRAGONS
        - [ ] Text bomb!!!
- [ ] Display upgrade
    - [ ] Nicer welcoming
    - [ ] Messages border
    - [ ] Color?

**Comment by klotzambein** [comment]
Maybe add a network protocoll (more complex than just sending messages back and forth unencrypted)
